### ISSUE TITLE
 RuntimeError on MaxOS

### ISSUE THREAD

**Issue by yingjerkao** [kaihsin/Cytnx#108]
Imported from email by Yu-Cheng Lin

I've installed the package ( 0.7.6a) on MacOS (v12.4, Intel processor) using conda install  and encountered some problems while using UniTensor. A simple example:
```
T = cytnx.UniTensor(cytnx.ones([5,5,5,5,5]), rowrank = 3)
s, u, vt = cytnx.linalg.Svd(T)
```
I got an error message as follows:
```
#Traceback (most recent call last):
#  File "xxx.py", line 9, in <module>
#    s, u, vt = cytnx.linalg.Svd(T)
#RuntimeError:
# Cytnx error occur at virtual void cytnx::DenseUniTensor::Init_by_Tensor(const cytnx::Tensor &, const bool &, const cytnx::cytnx_int64 &)
# error: [ERROR][Init_by_tensor] setting is_diag=True should have input Tensor to be rank-1 with diagonal elements.
# file : /Users/runner/minicondaL/conda-bld/cytnx_1654426663544/work/src/DenseUniTensor.cpp (98)
```
Similar messages showed up while building the evolution operator for iTEBD. On the other hand, I didn't see any warnings or error messages when I was installing the package.

There are no such issues on Ubuntu Linux as far as I've tested.

**Comment by jeffry1829** [comment]
Hi! This should have been solved by #107
