### ISSUE TITLE
SVD function name and arguments

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#117]
Some comments For Svd function:
1. I suggest combining `Svd_truncate` and `Svd`, and setting whether we want to truncate by an arguments `truncate=True/False`.
2. In `Svd_truncate`, I suggest normalizing the singular values by default and giving an argument `normalize=False` if the user does not want to normalize them.

**Comment by kaihsin** [comment]
1. I disagree with the first point, as truncation has more arguments and options, especially when dealing with blockUniTensor. We will remain Svd_truncate and Svd as two separate functions. 

2. I suggest we add an additional normalize function at UniTensor level. The reason for that is the user will not get confused when setting return_err=True when calling Svd_truncate, and it's easy to read in the code. 

We don't want millions of arguments in a single function calls

**Comment by chiamin** [comment]
1. OK
2. That would be also good. Do we have the normalize function already? If so the issue can be closed.

**Comment by kaihsin** [comment]
UniTensor.normalize() is added and will be released along with 0.9.1

**Comment by kaihsin** [comment]
This is officially launched with v0.9.1
