### ISSUE TITLE
Initialize cytnx.cytnx.Tensor in Python

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#118]
I suggest supporting the following way of initialization a cytnx.cytnx.Tensor and a UniTensor:

`a = cytnx.cytnx.Tensor([[0,1],[0,0]])`

**Comment by kaihsin** [comment]
1. the user should not call cytnx.cytnx.Tensor. It should be cytnx.Tensor.
2. We can discuss how to support list of list, so it doesn't get confused with the specification of shapes

**Comment by chiamin** [comment]
looking back on this I don't think it is necessary for now. I will close it.
