### ISSUE TITLE
norm for a UniTensor

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#124]
I suggest defining a function `norm` that takes a `UniTensor` as the input argument and returns a real number.

**Comment by jeffry1829** [comment]
Hi, there's DenseUniTensor::Norm() avaliable.
I'll try to add linalg::Norm for DenseUniTensor.

**Comment by chiamin** [comment]
Can we make a global function rather than a member function, and take the argument as any UniTensor (with or without quantum numbers) and compute the norm? I think a global function is more suitable in this case.

**Comment by kaihsin** [comment]
@chiamin Extenability-wise, It's actually better to keep implementation for each Type of UniTensor (Dense,Sparse...) Instead of implementing them in a global function and use if/else to switch. 

So that implementations are isolated and specialized by child class

**Comment by chiamin** [comment]
Can we just overlap the function?
