### ISSUE TITLE
Access elements in a UniTensor

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#125]
I think we need an easier way to access an arbitrary element in a `UniTensor`. The current way seems to first convert a `UniTensor` to a `Tensor`, and then use `.item()` to get the element. We should have a way to directly access the element without converting, if possible. Ideally, the function may look like
```
A[0,1,2]
```

Also, I would like to have this function even for `UniTensor` with quantum numbers.

**Comment by kaihsin** [comment]
Not really. You can use at() to get element for both UniTensor and Tensor

**Comment by kaihsin** [comment]
Should we close this? please use at()

**Comment by chiamin** [comment]
Yes I will close it.
