### ISSUE TITLE
Remove UniTensor.Dagger()

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#129]
The current `Dagger` function will change the order and the `rowrank` of the indices, in a quite confusing way. Since in a general case we should think of working with tensors rather than matrices, I suggest removing this function. A meaningful usage of `Dagger` function could be when one wants to reverse the arrows when there are quantum numbers. (This is the design of ITensor.) Besides this, the `Dagger` function is redundant.

**Comment by kaihsin** [comment]
The behavior of the Dagger is now changed, so the order does not changed. after v0.9
