### ISSUE TITLE
cytnx.linalg.Lanczos_Gnd_Ut need to be checked

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#132]
We may want to check `Lanczos_Gnd_Ut` algorithm for the following reason. In computing the ground state of transverse-field Ising model by DMRG, using `Lanczos_Gnd_Ut` obtains the correct energy, but it's "harder" to get a symmetry-breaking state for a small transverse field. Using Scipy Lanczos or ITensor Davison algorithm tends to obtain symmetry-breaking states more easily.

**Comment by j9263178** [comment]
It is found that `Lanczos_ER` can also reproduce symmetry-breaking state well (the reason why `Lanczos_Gnd_Ut` fails to do so might be its bad ability to converge)

**Comment by chiamin** [comment]
I thought `Lanczos_ER` and `Lanczos_Gnd_Ut` are doing the same thing but just having different input types. What are their differences?

**Comment by j9263178** [comment]
> I thought `Lanczos_ER` and `Lanczos_Gnd_Ut` are doing the same thing but just having different input types. What are their differences?

`Lanczos_ER` uses explicitly restarted while `Lanczos_Gnd` is the naive Lanczos implementation. `Lanczos_ER` and  `Lanczos_Gnd` takes the cytnx.Tensor type as input while `Lanczos_Gnd_Ut` takes cytnx.UniTensor.

**Comment by j9263178** [comment]
`Lanczos_Gnd_Ut` can also produce symmetry-breaking state, just need slightly more dmrg sweep than `Lanczos_ER` to converge.

**Comment by ianmccul** [comment]
This is useful historical context for the broader Krylov audit in #900 and the more specific `Lanczos_Gnd_Ut`/`Tridiag` issue in #903.

The current concern is not just whether `Lanczos_Gnd_Ut` can eventually converge in some DMRG workflows, but whether its breakdown handling, residual handling, and failure reporting are numerically well-defined.

Opened by Codex on behalf of @ianmccul.
