### ISSUE TITLE
Rename cytnx.arange to cytnx.arrange

### ISSUE THREAD

**Issue by manuschneider** [kaihsin/Cytnx#151]
Would be a more common naming convention.
Would concern the documentation as well.

**Comment by j9263178** [comment]
Hi, I find popular tensor libs like numpy and torch all use "arange" so maybe it's better we stick to it.

**Comment by manuschneider** [comment]
I thought the name comes from the English word 'arrange', but it seems that it is shorthand for 'arrayrange'. Therefore the name convention in numpy etc and we should sure stick to it.
