### ISSUE TITLE
creating Tensor with from_storage() does not work

### ISSUE THREAD

**Issue by manuschneider** [kaihsin/Cytnx#156]
I followed the user guide (3.1.4. Tensor from Storage [v0.6.6+]) to create a tensor from storage. However, when I try to print, there is an Error. It seems 

In Python:

A = cytnx.Storage(10);
B = cytnx.Tensor.from_storage(A);

print(A)
print(B)

Output>>

dtype : Double (Float64)
device: cytnx device: CPU
size  : 10
[ 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 ]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 9
      6 C = cytnx.Tensor.from_storage(A.clone());
      8 print(A)
----> 9 print(B)

RuntimeError: 
# Cytnx error occur at virtual void cytnx::Storage_base::PrintElem_byShape(std::ostream&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&)
# error: [ERROR] call PrintElem_byShape directly on Void Storage.
# file : /home/kaihsinwu/.pyenv/versions/anaconda3-2023.03/conda-bld/cytnx_1680994953300/work/src/Storage_base.cpp (177)

**Comment by kaihsin** [comment]
This is a pybind wrapper bug, and is fixed on 
[d386d0a](https://github.com/kaihsin/Cytnx/commit/d386d0a76448005b5b5f138e9b149cd9b2005833)

It will be released with next iteration v0.9.1
