### ISSUE TITLE
[API] (Suggestion) feed in network by labels

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#158]
I suggest using labels rather than index order when inputting tensors into a Network. Here is the proposed syntax.

Suppose I want to do a contraction of A and B matrices and set the outcome labels to j1 and j2
i1---(A)---i2-i3---(B)---i4  =  j1---Re---j2

I first define a Network as usual, where 0, 1, 2 are dummy indices only available in the network
0---(T1)---1-1---(T2)---2  =  0---out---1

        Define Network:
            T1: 0, 1
            T2: 2, 1
            remain: 0, 2
            out: 0, 1

When I feed in the tensors, I suggest to do the following. (Suppose N is the name of the network)

            N.PutUniTensor ("T1", A, (i1, i2))
            N.PutUniTensor ("T2", B, (i4, i3))
            N.out_label ((j1, j2))

In this way, one explicitly specifies the labels to the dummy indices and does not rely on the order of the indices. We also specify the outcome labels.

**Comment by j9263178** [comment]
[309c5a4](https://github.com/kaihsin/Cytnx/commit/309c5a42322f2444513d133a1e45a2b664502142)
