### ISSUE TITLE
[API] (Question) slice tensor

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#160]
Do we support setting a UniTensor by a subtensor? For example, if I want to set an MPO tensor that has virtual indices v1 and v2 as the 1st and the 3rd indices, can I do something like

```
M[0,:,1,:] = Sz
```

where Sz is a matrix? This would be convenient in making an MPO.

**Comment by j9263178** [comment]
It is not supported for UniTensor with type either dense or have symmetry.
(Note that for dense Unitensor you can achieve this by simply retrieving its Tensor first.)
