### ISSUE TITLE
[API] (Suggestion) cytnx.BD_KET

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#161]
I suggest changing

```
bond = cytnx.Bond(cytnx.BD_KET, [[0]], [1])
```

to

```
bond = cytnx.Bond(dir="in", dims=[1], qns=[[0]])
```

just for readability.

**Comment by kaihsin** [comment]
There is a  BD_IN alias for BD_KET

**Comment by chiamin** [comment]
Thanks for the reminder. If you think it is not worth changing you can close the issue.
