### ISSUE TITLE
Device.Print_Property() does not seem to be available from python

### ISSUE THREAD

**Issue by manuschneider** [kaihsin/Cytnx#162]
I tried to run the code in '2.2. Number of GPUs' of the documentation. However, Device.Print_Property() does not seem to be available from the Python API.?

I am using cytnx_cuda from conda (where the cytnx version is still 0.7.1a and python 3.8 must be used instead of 3.9).

In Python:

import cytnx

print(cytnx.Device.Ncpus)
print(cytnx.Device.Ngpus)
cytnx.Device.Print_Property();

Output>>
16
1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 3
      1 print(cytnx.Device.Ncpus)
      2 print(cytnx.Device.Ngpus)
----> 3 cytnx.Device.Print_Property();

AttributeError: module 'cytnx.cytnx.Device' has no attribute 'Print_Property'

___________________________________
Similarly, Device.getname(0) cannot be called.

print(cytnx.Device.getname(0))

**Comment by j9263178** [comment]
Fixed in [1f95e79](https://github.com/kaihsin/Cytnx/commit/1f95e799bb3cc7f20e26139995e2e6229d57516d).
