### ISSUE TITLE
Add labels in UniTensor constructor

### ISSUE THREAD

**Issue by manuschneider** [kaihsin/Cytnx#175]
When creating a UniTensor by one of the constructors, a name can be defined directly. However, the labels cannot. One has to use .relabels_() for this.

I would suggest to add an optional argument `labels` to do this directly.

The command that I use so far, `T = cytnx.UniTensor(cytnx.random.normal([3,4], mean=0, std=1), name="T").relabels_((["t_0","t_1"]);`
is not so well readable.

**Comment by kaihsin** [comment]
duplicated with #178, and solved
