### ISSUE TITLE
Set labels when create a UniTensor by a Tensor

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#178]
If I create a UniTensor from a Tensor, I cannot give labels at the same time. Below is the code and the error message. I suggest allowing user to set labels when creating a UniTensor.

```
import cytnx
# create a rank-3 tensor with shape [2,3,4]
T = cytnx.arange(2*3*4).reshape(2,3,4)
# convert to UniTensor:
uniT = cytnx.UniTensor(T,labels=["a","b","c"])
```

Error message:
Total elem: 24
type  : Double (Float64)
cytnx device: CPU
Shape : (2,3,4)
[[[0.00000e+00 1.00000e+00 2.00000e+00 3.00000e+00 ]
  [4.00000e+00 5.00000e+00 6.00000e+00 7.00000e+00 ]
  [8.00000e+00 9.00000e+00 1.00000e+01 1.10000e+01 ]]
 [[1.20000e+01 1.30000e+01 1.40000e+01 1.50000e+01 ]
  [1.60000e+01 1.70000e+01 1.80000e+01 1.90000e+01 ]
  [2.00000e+01 2.10000e+01 2.20000e+01 2.30000e+01 ]]]

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    uniT = cytnx.UniTensor(T,labels=["a","b","c"])
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. cytnx.cytnx.UniTensor()
    2. cytnx.cytnx.UniTensor(Tin: cytnx.cytnx.Tensor, is_diag: bool = False, rowrank: int = -1)
    3. cytnx.cytnx.UniTensor(bonds: List[cytnx.cytnx.Bond], labels: List[int] = [], rowrank: int = -1, dtype: int = 3, device: int = -1, is_diag: bool = False)
    4. cytnx.cytnx.UniTensor(bonds: List[cytnx.cytnx.Bond], labels: List[str] = [], rowrank: int = -1, dtype: int = 3, device: int = -1, is_diag: bool = False)

Invoked with: ; kwargs: labels=['a', 'b', 'c']

**Comment by kaihsin** [comment]
added in 95a9b3f90295c8725ce5b2110acbe052255961ee

**Comment by chiamin** [comment]
Hi Kai-Hsin,

Has the setting-label argument been added, and if so, has it been pushed to
the newest version? I tried to update cytnx in conda but still cannot set
labels. Can you please let me know when it is updated? Thanks.

Chia-Min

Kai-Hsin Wu ***@***.***> 於 2023年6月29日 週四 上午7:23寫道：

**Comment by kaihsin** [comment]
It's added on the commit, not publish yet.

**Comment by chiamin** [comment]
Can you let me know when you publish it? Thanks.

Kai-Hsin Wu ***@***.***> 於 2023年6月29日 週四 上午10:24寫道：

**Comment by kaihsin** [comment]
This is not an urgent thing need to go pub immediately, it will update along with other things on next version

**Comment by chiamin** [comment]
I will need this to test the example code in the draft so that I can make
sure all the examples actually work as expected. I would appreciate it if
you can publish it sooner.

Kai-Hsin Wu ***@***.***> 於 2023年6月29日 週四 下午3:57寫道：

**Comment by kaihsin** [comment]
It will go along with batch gemm, once that issue is resolved by
Chang-Teng.

**Comment by chiamin** [comment]
OK got it.

Kai-Hsin Wu ***@***.***> 於 2023年6月29日 週四 下午4:13寫道：

> It will go along with batch gemm, once that issue is resolved by
> Chang-Teng.
>
>
>

**Comment by chiamin** [comment]
Hi. Will you join the meeting now?

https://zoom.us/j/98916958275?pwd=eGhhNTJ2U2RUUkJSbUcweDVXVm96QT09
<https://www.google.com/url?q=https://zoom.us/j/98916958275?pwd%3DeGhhNTJ2U2RUUkJSbUcweDVXVm96QT09&sa=D&source=calendar&usd=2&usg=AOvVaw3HclZz8R11D1kdHoQ39KvM>

Chia-Min Chung ***@***.***> 於 2023年6月29日 週四 下午4:15寫道：

> OK got it.
>
> Kai-Hsin Wu ***@***.***> 於 2023年6月29日 週四 下午4:13寫道：
>
>> It will go along with batch gemm, once that issue is resolved by
>> Chang-Teng.
>>
>>
>>
