### ISSUE TITLE
function Lanczos_ER does not exist anymore

### ISSUE THREAD

**Issue by manuschneider** [kaihsin/Cytnx#185]
In the guide, in"10.2. Lanczos solver" there is a function call
cytnx.linalg.Lanczos_ER(op,k=1,Tin=v0).

But Lanczos_ER does not exist.
Was this renamed or is a different function used now? The guide should be updated.

**Comment by j9263178** [comment]
Hi, for pypind I found the functions are commented out : https://github.com/kaihsin/Cytnx/blob/0ae00618d01b404f3832fa2c270e25079d65ddca/pybind/linalg_py.cpp#L382

I think the developer wants to deprecated Lanczos_ER and Lanczos_Gnd and encourage users to use simply Lanczos now (where the API can be found in https://kaihsinwu.gitlab.io/cytnx_api/v0.9.1/namespacecytnx_1_1linalg.html) and yes we should update the guide.
