### ISSUE TITLE
package name in conda

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#20]
If I do a conda install
````
conda install -c kaihsinwu cytnx_38
````

when I do conda list, the package name is cytnx_38
````
conda list |grep cytnx
# packages in environment at /Users/pcchen/anaconda3/envs/cytnx_py38:
cytnx_38                  0.5.6a           py38h0a44026_0    kaihsinwu
````

Is it possible to display the package name as ``cytnx``? Otherwise, I tend to try ``import cytnx_38``.

**Comment by kaihsin** [comment]
This is changed at the latest push. See [Install guide](https://kaihsinwu.gitlab.io/Cytnx_doc/install.html ). 

For CPU only:
`conda install -c kaihsinwu cytnx`

For CUDA support:
`conda install -c kaihsinwu cytnx_cuda`
