### ISSUE TITLE
Compilation fail due to no conversion from Scalar to complex types

### ISSUE THREAD

**Issue by yingjerkao** [kaihsin/Cytnx#23]
The latest commit 23c3612b9bececd035b75994af7b1ad2a7dd9d55 fails to compile due to the following errors.

`/Users/yjkao/cytnx/src/linalg/linalg_internal_cpu/Div_internal.cpp(104): error: no suitable user-defined conversion from "cytnx::Scalar" to "cytnx::cytnx_complex128" exists
                  cytnx_complex128 a = 1./_Rin[0];
                                       ^

/Users/yjkao/cytnx/src/linalg/linalg_internal_cpu/Div_internal.cpp(823): error: no suitable user-defined conversion from "cytnx::Scalar" to "cytnx::cytnx_complex64" exists
                  cytnx_complex64 a = 1./_Rin[0];
                                      ^

/Users/yjkao/cytnx/src/linalg/linalg_internal_cpu/Div_internal.cpp(1412): error: no suitable user-defined conversion from "cytnx::Scalar" to "cytnx::cytnx_complex64" exists
                  cytnx_complex64 a = 1./cytnx_complex64(_Rin[0],0);
                                      ^
`

This can be reproduced on both Linux and Mac

**Comment by kaihsin** [comment]
Hi, 

Please try the latest commit.  https://github.com/kaihsin/Cytnx/commit/e525ae114327f39ac71e7d5d02341f79f756f3ca

The code should be able to compile successfully on both linux and  Mac. Please let me know if the issue is solved.
