### ISSUE TITLE
Different results in c++ and python for complex evaluation

### ISSUE THREAD

**Issue by j9263178** [kaihsin/Cytnx#28]
### In python :

sx = cytnx.physics.spin(0.5,'x')
sy = cytnx.physics.spin(0.5,'y')
sp = sx+1j*sy
sm = sx-1j*sy
print(sp)
print(sm)

### Results in python : 

Total elem: 4
type  : Complex Double (Complex Float64)
cytnx device: CPU
Shape : (2,2)
[[0.00000e+00+0.00000e+00j 1.00000e+00+0.00000e+00j ]
 [0.00000e+00+0.00000e+00j 0.00000e+00+0.00000e+00j ]]

Total elem: 4
type  : Complex Double (Complex Float64)
cytnx device: CPU
Shape : (2,2)
[[0.00000e+00+0.00000e+00j 0.00000e+00+0.00000e+00j ]
 [1.00000e+00+0.00000e+00j 0.00000e+00+0.00000e+00j ]]

### In c++ : 

std::complex<double> j = (0, 1);
auto Sx = physics::spin(0.5,'x');
auto Sy = physics::spin(0.5,'y');
auto Sp = Sx + j*Sy;
auto Sm = Sx - j*Sy;
std::cout<<Sp<<std::endl;
std::cout<<Sm<<std::endl;

### Results in c++ : 

Total elem: 4
type  : Complex Double (Complex Float64)
cytnx device: CPU
Shape : (2,2)
[[0.00000e+00+0.00000e+00j 5.00000e-01-5.00000e-01j ]
 [5.00000e-01+5.00000e-01j 0.00000e+00+0.00000e+00j ]]

Total elem: 4
type  : Complex Double (Complex Float64)
cytnx device: CPU
Shape : (2,2)
[[0.00000e+00+0.00000e+00j 5.00000e-01+5.00000e-01j ]
 [5.00000e-01-5.00000e-01j 0.00000e+00+0.00000e+00j ]]

**Comment by kaihsin** [comment]
Hi are you sure the C++ code can be compiled? 

1. for C++, complex need to specify the template, e.g. complex<float> or complex<double>. For cytnx. the equivalent is cytnx_complex64 and cytnx_complex128. 
2. I think jSy is invalid.

**Comment by j9263178** [comment]
my original code is 

```    
std::complex<double> j = (0, 1);
auto Sx = physics::spin(0.5,'x');
auto Sy = physics::spin(0.5,'y');
auto Sp = Sx + j*Sy;
auto Sm = Sx - j*Sy;
std::cout<<Sp<<std::endl;
std::cout<<Sm<<std::endl;
```

**Comment by kaihsin** [comment]
Hi, this is actually not a bug in cytnx. 

for initialize complex number in C++, one should use {0,1} instead of (0,1).
