### ISSUE TITLE
invalid narrowing conversion from "unsigned long long" to "long long"

### ISSUE THREAD

**Issue by yingjerkao** [kaihsin/Cytnx#32]
System: Mac OS X 10.15.7 (Catalina)
Compiler: Intel icpc version 2021.1
How to reproduce: Build commit 32b62ff5891f92df72ed08d4a615d3b6813836a3
Short summary: Compiler gives error due to the implicit conversion from `unsigned int` to `int`. I believe this is related in the list initialization. 
Possible Fix: use `static_cast` to explicitly cast the type
References: [Surprises and Undefined Behavior From Unsigned Integer Promotion](https://jeffhurchalla.com/2019/01/16/c-c-surprises-and-undefined-behavior-due-to-unsigned-integer-promotion/)

`====================[ Build | all | Debug ]=====================================
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/yjkao/cytnx/cmake-build-debug --target all -- -j 3
[  1%] Building CXX object CMakeFiles/cytnx.dir/src/linalg/Lstsq.cpp.o
[  1%] Building CXX object CMakeFiles/cytnx.dir/src/linalg/linalg_internal_cpu/Matmul_internal.cpp.o
[  2%] Building CXX object CMakeFiles/cytnx.dir/src/linalg/linalg_internal_cpu/Matmul_dg_internal.cpp.o
/Users/yjkao/cytnx/src/linalg/Lstsq.cpp(38): error #3291: invalid narrowing conversion from "unsigned long long" to "long long"
                  bin = Tensor::from_storage(bstor).reshape({n,nrhs});
                                                             ^

/Users/yjkao/cytnx/src/linalg/Lstsq.cpp(38): error #3291: invalid narrowing conversion from "unsigned long long" to "long long"
                  bin = Tensor::from_storage(bstor).reshape({n,nrhs});
                                                               ^

/Users/yjkao/cytnx/src/linalg/Lstsq.cpp(55): error #3291: invalid narrowing conversion from "unsigned long long" to "long long"
                  sol.reshape_({n,nrhs});
                                ^

/Users/yjkao/cytnx/src/linalg/Lstsq.cpp(55): error #3291: invalid narrowing conversion from "unsigned long long" to "long long"
                  sol.reshape_({n,nrhs});
                                  ^

make[2]: *** [CMakeFiles/cytnx.dir/src/linalg/Lstsq.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/cytnx.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by kaihsin** [comment]
The only happens in using icpc to build. We are currently investigating this issue, but we are currently lowering this priority.
