### ISSUE TITLE
Conda install: Supported python version

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#41]
Currently, conda install supports python 3.6/3.7/3.8. Do we want to support python 3.9/3.10?

````
Specifications:

  - cytnx -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
````

**Comment by kaihsin** [comment]
I think the plan is to support 3.7-3.9 for the next iteration 0.7.5 or 0.7.6

**Comment by kaihsin** [comment]
v076 is now online, with support version 3.7/3.8/3.9
