### ISSUE TITLE
U(1) tensor contraction optimization

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#43]
There may be some room to further optimize the U(1) contraction function, in particular the contiguous function. This should not be in the highest priority, but it may worth to explore it a bit more. One may want to look that again the CPU profile for the current version (using .at or another internal function). The goal (or dream) is to see the contiguous function eventually becomes cheaper than the BLAS matrix multiplication for a large but achievable D (which might or might not be possible).

**Comment by j9263178** [comment]
Here is the profiling comparison (with valgrind) of the Dense and U(1) env-MPSsite contraction task 
![fixed1](https://user-images.githubusercontent.com/54367491/163711419-f29ab214-dc06-4259-a240-152ea575d359.jpg)
![fixed2](https://user-images.githubusercontent.com/54367491/163711428-a7138e72-8087-4c9e-8bb4-a780ff681d94.jpg)
