### ISSUE TITLE
Math Libraries

### ISSUE THREAD

**Issue by yingjerkao** [kaihsin/Cytnx#45]
A couple of existing GPU libraries wrapping CuSolver/CuBlas or Magma

1. ArrayFire
https://arrayfire.com
https://github.com/arrayfire/arrayfire

2. Armadillo
https://gitlab.com/conradsnicta/armadillo-code

**Comment by yingjerkao** [comment]
Also BLAS for sparse matrics
https://graphblas.org

**Comment by kaihsin** [comment]
I think both of them don't use magma

**Comment by yingjerkao** [comment]
ArrayFire has magma backend

https://github.com/arrayfire/arrayfire/tree/master/src/backend/opencl/magma

**Comment by yingjerkao** [comment]
OneMKL now provides  `MKLConfig.cmake` module for MKL integration
https://www.intel.com/content/www/us/en/develop/documentation/onemkl-macos-developer-guide/top/getting-started/cmake-config-for-onemkl.html

**Comment by kaihsin** [comment]
Yes. I am aware of this. This is not compatible with cmake default version on some of the platform and conda package. So currently we will not use this

**Comment by kaihsin** [comment]
we hooked up with magma after v0.9.
