### ISSUE TITLE
Documentation files in the library

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#46]
I found that there is a folder "docs" for the documentation in the repository. This folder is rather big (32M). Do we want to keep this in the repository? I personally will prefer to mainly just a website, and no need to put the documentation in the repository.

Also there is a file include/utils/vec_io.hpp.gch that is also big (36M). What is this file and why is it so big?

**Comment by kaihsin** [comment]
vec_io.hpp.gch should be removed now. 

Currently, the docs for APIs are hosted by doxygen. Will move to another repo later

**Comment by kaihsin** [comment]
[11728d1](https://github.com/kaihsin/Cytnx/commit/11728d1fb5b1f68b3f6e88f90e3b19f31c998122) 

The API docs is moved to DocAPI branch, and host there. master repo will no longer include docs/ 
User can still build the API by themself via doxygen.
