### ISSUE TITLE
pybind11

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#47]
I wonder if we can include pybind11 as a submodule? 

References:
* https://pybind11.readthedocs.io/en/stable/installing.html
* https://pybind11.readthedocs.io/en/stable/compiling.html#compiling

**Comment by kaihsin** [comment]
In principle we could, but then we need to separate them in CMake for conda-build

**Comment by kaihsin** [comment]
We stick on this for v0.9.
