### ISSUE TITLE
[API] Bond constructor

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#51]
I have the following suggestions about the constructor of the class `Bond`.

1. For the argument `bd_type`, `BD_REG`, `BD_Ket` and `BD_Bra` are not good names. I would suggest to change them to for example dir::none, dir::in, dir::out or so.
2. Not clear to me how to include two different quantum numbers, for example U(1) and Z_2, in the same `Bond`.

**Comment by kaihsin** [comment]
KET, BRA make more sense physically, but it could be confusing in terms of TN. In 45649aa an alias is made, 

so one can also assign 
BD_IN = BD_KET
BD_OUT = BD_BRA
BD_NON = BD_REG
