### ISSUE TITLE
[API] UniTensor, rowrank

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#52]
It seems to me that `rowrank` is not a necessary piece for a tensor. I would prefer to remove it if possible.

**Comment by pcchen** [comment]
It is necessary for UniTensor. When one wants to map a UniTensor to a matrix to perform diagonalization or SVD, one needs the rowrank to uniquely define the matrix.

**Comment by chiamin** [comment]
To me it is more natural to assign this information when doing SVD or so, rather than put it in the tensor definition.

**Comment by pcchen** [comment]
Maybe that is true. 

But, this is also related to how you keep symmetry.

If the bond has no concept of direction. Then you need something like Q_row=Q_col in a symmetry tensor. Then you need to know row rank. 

My experience is that, there are some advantage in "always have a default corresponding matrix".
