### ISSUE TITLE
[Compile] No way to disable openmp 

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#55]
## Enviroment
Ubuntu 18.04 LTS

## Problem
First, if I install cytnx with mkl,cuda,hptt off, I need to run `conda install openblas` , which should be stated in user manual.

Second, if I install cytnx with mkl,cuda,hptt off, the CYTNX_CXXFLAGS defined by `CYTNX_CXXFLAGS := $(shell python -c "exec(\"import sys\nsys.path.append(\'$(CYTNX_ROOT)\')\nimport cytnx\nprint(cytnx.__cpp_flags__)\")")
` won't contain -fopenmp, which in term cause errors like `undefined reference to 'GOMP_parallel'`

Last, even if I install cytnx with mkl,cuda,hptt off, there's still -DUNI_OMP in CYTNX_CXXFLAGS, and seems like I can't find a way to disable openmp easily.

Thanks!

## Sidenote
`CYTNX_CXXFLAGS := $(shell python -c "exec(\"import sys\nsys.path.append(\'$(CYTNX_ROOT)\')\nimport cytnx\nprint(cytnx.__cpp_flags__)\")")
` isn't valid syntax for bash. I wonder what syntax is it.

**Comment by kaihsin** [comment]
Openmp can be turned off when cmake installing with -DUSE_OMP=off. 
By default Openmp is =on. 

I will check the flags with MKL=off and OMP=on later.
