### ISSUE TITLE
[Compile] Duplicate option -std=c++??

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#56]
## Enviroment
Ubuntu 18.04.1 LTS

## Problem
If I install cytnx with mkl,hptt on, cuda off. the CYTNX_CXXFLAGS defined by `CYTNX_CXXFLAGS := $(shell python -c "exec(\"import sys\nsys.path.append(\'$(CYTNX_ROOT)\')\nimport cytnx\nprint(cytnx.__cpp_flags__)\")")` will contain both -std=c++17 and -std=c++11, we should remove one.

Thanks!

**Comment by kaihsin** [comment]
This should be removed in 6cef6df
