### ISSUE TITLE
[API] vector<cytnx_uint64> or vector<cytnx_int64>

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#57]
## Problem
Tensor::zeros receive vector<cytnx_uint64> parameter while Tensor::reshape receive vector<cytnx_int64> parameter. We should choose one or overloading.

Thanks!

**Comment by kaihsin** [comment]
reshape should be overloaded with uint64 starting from 91ec4eaee9be1fbdd444894983bb3019c2a3ea1c. 

The reason for reshape() to accept signed int is because we allow the value "-1" to auto calculate the remaining dimension for a rank.
