### ISSUE TITLE
[Optimization] Vec_erase optimize

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#58]
## Problem
In https://github.com/kaihsin/Cytnx/blob/master/src/utils/vec_erase.cpp#L15
We can first iterate over `eraseper`, and store 1 to the vector\<bool\>(in.size())[erase index] (bad idea) or boost::dynamic_bitset(in.size())[erase index]. And pushing elements to `out` vector while checking if the element is to be erased.

Moreover, we could use [pbds hashtable](https://codeforces.com/blog/entry/60737)
```
#include <ext/pb_ds/assoc_container.hpp>
using namespace __gnu_pbds;
gp_hash_table<int, int> table;
```
to store the index of elements to delete.

This, we can avoid O(n lg n) sorting and O(n^2) erasing where n is the length of `eraseper`.

Thanks!

**Comment by kaihsin** [comment]
I think PBDS only works for gnu compiler?

**Comment by jeffry1829** [comment]
Seems like it supports icpc (https://gcc.gnu.org/onlinedocs/libstdc++/ext/pb_ds/prerequisites.html)
I didn't test it though

**Comment by jeffry1829** [comment]
EDIT: We shouldn't use hash table, since data range of `eraseper` lies in [0,len) where `len` certainly won't exceed 1e9
