### ISSUE TITLE
[Compile] cytnx.__cpp_lib__ gives the wrong folder name

### ISSUE THREAD

**Issue by j9263178** [kaihsin/Cytnx#59]
## Enviroment
aragorn

## Problem
After installing cytnx using auto_install.py, if we follow the user guide and run the following command in the installed folder (/home/j9263178/cytnx_debug_2/):
```
python -c "exec(\"import cytnx\nprint(cytnx.__cpp_lib__)\")"
```
gives
```
/home/j9263178/cytnx_debug_2/lib
```

However the installed lib folder name is "lib64".

**Comment by kaihsin** [comment]
Fixed in 0e8c45e
