### ISSUE TITLE
[Manual] Tell user UniTensor contains only one pointer member

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#60]
I suggest that we tell users in manual that UniTensor only contains one boost::intrusive_ptr and will free memory itself.

That, users won't consider maintaining UniTensor pointer array.

Thanks!

**Comment by kaihsin** [comment]
Do you think it is good? 
Maybe it's better to put a hierarchy in documentation if we want to do this, leaving those to something like "advance" page. 

Not every user know what is intrusive_ptr, currently we explain it by analogy to python variables/objects, and a page with "when will data copied"

**Comment by jeffry1829** [comment]
Oh, I misread that part! I think there's no need to add my description.

Thanks!
