### ISSUE TITLE
[Optimize] The reason why SparseTensor.contiguous call enormously large number of delete

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#61]
Someone I know told me the following:

Consider https://github.com/kaihsin/Cytnx/blob/master/src/Storage_base.cpp#L638 (`cytnx_error_msg(dtype != Type.Double, "[ERROR] type mismatch. try to get <double> type from raw data of type %s", Type.getname(dtype).c_str());`)

First, we should write `std::string typename = Type.getname(dtype)` before the function call, and then call function by `cytnx_error_msg(dtype != Type.Double, "[ERROR] type mismatch. try to get <double> type from raw data of type %s", typename.c_str());`

This is because std::string#c_str() returns an pointer to the string. But once we get c_str() pointer, the lifecycle of string ends, and c_str() points to deleted memory.

Second, in https://github.com/kaihsin/Cytnx/blob/master/src/Type.cpp#L96, whenever cytnx returns the typename, it copies to new string, hence the reason why there'll be new and delete in Storage#at().
To solve that, we should return std::string&

Third, in https://github.com/kaihsin/Cytnx/blob/master/src/Storage_base.cpp#L643, we might want to use reinterpret_cast.

Last, in https://github.com/kaihsin/Cytnx/blob/master/include/Type.hpp#L51, we might want to rewrite the struct to
```
struct{
uint8_t type; // 0:int_type 1:float type
union{
struct{bool is_unsigned;}int_type;
struct{bool is_complex;}float_type;
}
std::string typename;
unsigned int typeSize;
}
``` 
Since there shouldn't be unsigned float or unsigned complex, if we write like this, we can reduce the struct size as well as prohibit non-exist types.
Also note that, we should put 4 byte types to the tail of the struct for alignment.

Thanks!

**Comment by kaihsin** [comment]
@j9263178 could you check if all the delete all coming from the string? 

@jeffry1829 thanks! I will fix it later, if you want you can create a PR

**Comment by j9263178** [comment]
> @j9263178 could you check if all the delete all coming from the string?
> 
> @jeffry1829 thanks! I will fix it later, if you want you can create a PR

In my current internal function implementation (in which no .at() or .get_name() will be called) there are still delete operations from the contiguous() and takes about 1/6 computation time.
