### ISSUE TITLE
Network remove is_clone flag.

### ISSUE THREAD

**Issue by kaihsin** [kaihsin/Cytnx#76]
1. Remove the is_clone flag as it is no longer needed with the Contract having mv_elemL/R flags
2. Remove rowrank semi-colon in Network file.

**Comment by chiamin** [comment]
I just want to make a commend that, this modification potentially can raise errors to the current version. You may want to test the case, for example, that two tensors in the network are the same.

**Comment by jeffry1829** [comment]
Why removing is_clone flag but not set the default to False?
For cases we want to do A.contract(A) with Network, this might fail?

**Comment by j9263178** [comment]
This is done in #95 .
