### ISSUE TITLE
[API] rowrank

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#79]
I recommend to give a default value to the `rowrank` argument when initializing a tensor. The indices for row and column respectively need to be specified when one want to represent a tensor to a matrix, for example in calling `svd`. One need to make sure that all the functions that use a tensor as a matrix are properly modified.

**Comment by kaihsin** [comment]
[00797a0](https://github.com/kaihsin/Cytnx/commit/00797a04993051c049bbbff270fcdbe17d280b5e) The rowrank is now optional for UniTensor without symmetry.
