### ISSUE TITLE
[Suggestion] Establish code style

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#88]
We may establish coding style via clang-format?
Such as maximum line length set to 80-100?

Also, once established, we could use clang-format to reformat whole project.

**Comment by yingjerkao** [comment]
We should definitely do this. 
@kaihsin already has a convention for naming variables and functions, and maybe we should put those in words.

**Comment by kaihsin** [comment]
See Documentation, a new chapter was added to describe the naming convention.

**Comment by IvanaGyro** [comment]
Is [Function Naming convention](https://kaihsinwu.gitlab.io/Cytnx_doc/convention.html) the chapter mentioning the naming convention?

**Comment by kaihsin** [comment]
Yes. Except their first point, i actually want to change that to be
pydantic
