### ISSUE TITLE
[Discussion] Some concerns with WSL2 and linking library

### ISSUE THREAD

**Issue by jeffry1829** [kaihsin/Cytnx#90]
After investigating `libiomp5.so: undefined reference to 'memcpy@GLIBC_2.14'` in WSL2 for a long time, I conclude the following problems and want to discuss how to solve this.

The original problem is:
When using WSL2, in the environment cytnx which is set as document says. When I use `g++ -I${CYTNX_INC} ${CYTNX_CXXFLAGS} test.cpp -o test ${CYTNX_LIB} ${CYTNX_LDFLAGS}` to compile files as stated in document, the following error pops up:
```
(cytnx) $g++ -I${CYTNX_INC} ${CYTNX_CXXFLAGS} test.cpp -o test ${CYTNX_LIB} ${CYTNX_LDFLAGS}
/home/petjelinux/anaconda3/envs/cytnx/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/petjelinux/anaconda3/envs/cytnx/lib/libiomp5.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
```

conda list shows:
```
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       1_gnu    conda-forge
```
notice the build 1_gnu, which uses memcpy@GLIBC_2.14 for libiomp5.so. (builds like 1_llvm use memcpy@GLIBC_2.2.5 instead. I'm not sure what determines the build of _openmp_mutex in conda. As much as I observed, in CentOS Linux release 7.9.2009, conda chose 1_llvm.)
(Found by `readelf --dyn-syms -W /home/petjelinux/anaconda3/envs/cytnx/lib/libiomp5.so | grep memcpy`)

Now, I want to find the libc.so.6 acquired by libiomp5.so.
Notice that in environment cytnx:
```
(cytnx) $ which ldd
/usr/bin/ldd
(cytnx) $ which ld
/home/petjelinux/anaconda3/envs/cytnx/bin/ld
```
seems like conda doesn't replace ldd, and it's very misleading if not noticed.(We may think libiomp5.so uses system libc.so.6)
To find which libc.so.6 does `/home/petjelinux/anaconda3/envs/cytnx/bin/ld` use [this](https://stackoverflow.com/a/21610523/5281422). I noticed conda uses `/home/petjelinux/anaconda3/envs/cytnx/x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6`.
Run `readelf --dyn-syms -W /home/petjelinux/anaconda3/envs/cytnx/x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 | grep memcpy`, I found that there's indeed no memcpy@GLIBC_2.14!
```
(cytnx) $readelf --dyn-syms -W /home/petjelinux/anaconda3/envs/cytnx/x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 | grep memcpy
   327: 0000000000091370     9 FUNC    WEAK   DEFAULT   12 wmemcpy@@GLIBC_2.2.5
   980: 00000000001010f0    27 FUNC    GLOBAL DEFAULT   12 __wmemcpy_chk@@GLIBC_2.4
  1091: 0000000000089720  1125 FUNC    GLOBAL DEFAULT   12 memcpy@@GLIBC_2.2.5
  1576: 0000000000089710     9 FUNC    GLOBAL DEFAULT   12 __memcpy_chk@@GLIBC_2.3.4
```

However, when using CMake, the project builds successfully? That's because cmake will add some linker option automatically. The critical one is `-Wl,--as-needed`, which prevent this error from happening when the project didn't use it. (The linker option can be found in `build/CMakeFiles/CMAKE_TARGET_NAME.dir/link.txt`)

Also, I found that when I remove the line `target_link_libraries(cytnx PUBLIC Boost::boost ${LAPACK_LIBRARIES})` in Cytnx CMakeLists.txt, the project builds successfully without any problem, is that normal?(I haven't investigate whether LAPACK_LIBRARIES are used in Cytnx)

In conclusion, we should report this to conda, -Wl,--as-needed, or use `patchelf` as a workaround to this problem?
(Using `strings /home/petjelinux/ana
conda3/envs/cytnx/x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 | grep GLIBC_`, I found that seems like conda glibc is in version GLIBC_2.12, **_maybe_** it's possible to lower cytnx glibc version acquirement to 2.12?)

(Note that if I use naive way: `g++ -L/system/lib/path`, some other undefined references appears, and I haven't look into those)
```
(cytnx) $g++ test.cpp -L/lib/x86_64-linux-gnu -L/home/petjelinux/anaconda3/envs/cytnx/lib -liomp5 -o test
/home/petjelinux/anaconda3/envs/cytnx/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/petjelinux/anaconda3/envs/cytnx/bin/../x86_64-conda-linux-gnu/sysroot/lib64/libpthread.so.0: undefined reference to `h_errno@GLIBC_PRIVATE'
/home/petjelinux/anaconda3/envs/cytnx/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/petjelinux/anaconda3/envs/cytnx/bin/../x86_64-conda-linux-gnu/sysroot/lib64/libpthread.so.0: undefined reference to `__libc_dl_error_tsd@GLIBC_PRIVATE'
/home/petjelinux/anaconda3/envs/cytnx/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/petjelinux/anaconda3/envs/cytnx/bin/../x86_64-conda-linux-gnu/sysroot/lib64/librt.so.1: undefined reference to `__vdso_clock_gettime@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
```

**Comment by kaihsin** [comment]
Have you tried to change _openmp_mutex from gnu to llvm?

**Comment by jeffry1829** [comment]
@kaihsin That works
